const state={resources:[],wic:null,program:null,impact:null,markers:[],zipLayers:[],activeCategory:'all',search:'',mode:'resources'};
const categoryColors={lilys:'#6c4f7c',wic:'#155f52',food:'#c27d25',housing:'#3674a4',health:'#b95568',family:'#9b7627',transportation:'#4f5e68'};
const map=L.map('map',{scrollWheelZoom:false}).setView([38.414,-82.431],13.5);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);

function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function primaryCategory(r){return r.category.includes('lilys')?'lilys':r.category[0];}
function markerIcon(r){const c=categoryColors[primaryCategory(r)]||'#555';return L.divIcon({className:'',html:`<div class="marker-pin" style="background:${c}"></div>`,iconSize:[19,19],iconAnchor:[9,9]});}
function directionsUrl(r){return `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(r.address)}`;}
function phoneHref(p=''){return `tel:${p.replace(/\D/g,'')}`;}
function filteredResources(){const q=state.search.trim().toLowerCase();return state.resources.filter(r=>{const cat=state.activeCategory==='all'||r.category.includes(state.activeCategory);const hay=[r.name,r.address,...r.services,...r.category].join(' ').toLowerCase();return cat&&(!q||hay.includes(q));});}
function popupHtml(r){return `<strong>${escapeHtml(r.name)}</strong><br><span>${escapeHtml(r.address)}</span><br><br><span>${r.services.map(escapeHtml).join(' • ')}</span><div class="card-actions"><a target="_blank" rel="noopener" href="${directionsUrl(r)}">Directions</a>${r.phone?`<a href="${phoneHref(r.phone)}">Call</a>`:''}${r.website?`<a target="_blank" rel="noopener" href="${r.website}">Website</a>`:''}</div>${r.verified===false?'<div style="font-size:.72rem;margin-top:7px;color:#7b6b39">Location detail should be re-verified before public launch.</div>':''}`;}
function clearResources(){state.markers.forEach(m=>map.removeLayer(m));state.markers=[];}
function clearZipLayers(){state.zipLayers.forEach(x=>map.removeLayer(x));state.zipLayers=[];}
function renderResources(){clearResources();clearZipLayers();const list=document.querySelector('#resourceList');list.innerHTML='';const shown=filteredResources();document.querySelector('#resultCount').textContent=`${shown.length} shown`;shown.forEach(r=>{const m=L.marker([r.lat,r.lng],{icon:markerIcon(r)}).addTo(map).bindPopup(popupHtml(r));state.markers.push(m);const card=document.createElement('article');card.className='resource-card';card.innerHTML=`<h4>${escapeHtml(r.name)}</h4><p>${escapeHtml(r.address)}</p><p>${r.services.slice(0,3).map(escapeHtml).join(' • ')}</p><div class="tags">${r.category.map(c=>`<span class="tag">${escapeHtml(c)}</span>`).join('')}</div><div class="card-actions"><a target="_blank" rel="noopener" href="${directionsUrl(r)}">Directions</a>${r.phone?`<a href="${phoneHref(r.phone)}">Call</a>`:''}${r.website?`<a target="_blank" rel="noopener" href="${r.website}">Website</a>`:''}</div>`;card.addEventListener('click',e=>{if(e.target.tagName!=='A'){map.setView([r.lat,r.lng],16);m.openPopup();}});list.appendChild(card);});document.querySelector('#mapNote').textContent='Resource locations are shown for navigation. Confirm current hours and service requirements with each organization.';}
function opportunityInterpretation(z){if(z.estimatedNotEnrolled2025<0)return 'The modeled estimate indicates participation meets or exceeds the modeled eligible population in this ZIP.';if(z.estimatedNotEnrolled2025<10)return 'The modeled participation gap is relatively small in this dataset.';if(z.estimatedNotEnrolled2025>=60)return 'This dataset shows a comparatively larger modeled opportunity for additional WIC reach.';return 'This dataset shows a modeled opportunity for additional WIC reach.';}
function renderOpportunity(){clearResources();clearZipLayers();const list=document.querySelector('#resourceList');list.innerHTML='';document.querySelector('#resultCount').textContent=`${state.wic.zipCodes.length} ZIP codes`;state.wic.zipCodes.forEach(z=>{const size=Math.max(46,Math.min(92,40+z.estimatedEligible/12));const icon=L.divIcon({className:'',html:`<div class="zip-bubble" style="width:${size}px;height:${size}px">${z.zip}</div>`,iconSize:[size,size],iconAnchor:[size/2,size/2]});const m=L.marker(z.center,{icon}).addTo(map).bindPopup(`<strong>ZIP ${z.zip}</strong><br>Estimated WIC eligible: <b>${z.estimatedEligible.toFixed(1)}</b><br>Active WIC clients (2025): <b>${z.activeClients2025}</b><br>Births: <b>${z.births}</b><br>Births below 185% poverty estimate: <b>${z.births185}</b><br><br>${opportunityInterpretation(z)}<br><small>Bubble is an approximate ZIP center, not a ZIP boundary.</small>`);state.zipLayers.push(m);const card=document.createElement('article');card.className='resource-card';card.innerHTML=`<h4>ZIP ${z.zip}</h4><p><strong>${z.estimatedEligible.toFixed(1)}</strong> estimated WIC eligible • <strong>${z.activeClients2025}</strong> active clients</p><p>${z.births} births • ${z.under5.toLocaleString()} children under age 5</p><p>${opportunityInterpretation(z)}</p>`;card.addEventListener('click',()=>{map.setView(z.center,14);m.openPopup();});list.appendChild(card);});map.fitBounds(L.latLngBounds(state.wic.zipCodes.map(z=>z.center)).pad(.15));document.querySelector('#mapNote').textContent='WIC opportunity bubbles use approximate ZIP centers for visualization. They are not ZIP boundaries and do not represent individual eligibility.';}
function setMode(mode){state.mode=mode;document.querySelector('#resourceMode').classList.toggle('active',mode==='resources');document.querySelector('#opportunityMode').classList.toggle('active',mode==='opportunity');if(mode==='resources')renderResources();else renderOpportunity();}
function setCategory(cat){state.activeCategory=cat;document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b.dataset.category===cat));setMode('resources');document.querySelector('#resources').scrollIntoView({behavior:'smooth'});}

function renderMetrics(){const v=state.program.valleyEW;const m=[{label:'Estimated WIC eligible across Huntington ZIPs 25701–25705',value:Math.round(state.wic.totals.estimatedEligible).toLocaleString(),note:'Planning estimate from uploaded WIC map data'},{label:'Cabell County active WIC families',value:state.program.cabellActiveFamilies.toLocaleString(),note:'County data workbook'},{label:'Valley East/West FY2026 mobile enrollment events',value:v.totalEvents.toLocaleString(),note:`Q1 ${v.q1Events} • Q2 ${v.q2Events} • Q3 ${v.q3Events} • Q4 ${v.q4Events}`},{label:'Valley East/West mobile enrollment hours',value:v.mobileEnrollmentHours.toLocaleString(undefined,{maximumFractionDigits:1}),note:`${(v.mobileEnrollmentShare*100).toFixed(1)}% of total outreach in workbook`}];document.querySelector('#metricGrid').innerHTML=m.map(x=>`<article class="metric-card"><div class="label">${x.label}</div><div class="value">${x.value}</div><div class="note">${x.note}</div></article>`).join('');}
function renderCharts(){new Chart(document.querySelector('#eligibleChart'),{type:'bar',data:{labels:state.wic.zipCodes.map(z=>z.zip),datasets:[{label:'Estimated WIC eligible',data:state.wic.zipCodes.map(z=>z.estimatedEligible),backgroundColor:'rgba(21,95,82,.78)',borderRadius:7}]},options:{responsive:true,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,grid:{color:'#edf1ef'}},x:{grid:{display:false}}}}});const v=state.program.valleyEW;new Chart(document.querySelector('#mobileChart'),{type:'line',data:{labels:['Q1','Q2','Q3','Q4'],datasets:[{label:'Mobile enrollment events',data:[v.q1Events,v.q2Events,v.q3Events,v.q4Events],borderColor:'#67507c',backgroundColor:'rgba(103,80,124,.12)',fill:true,tension:.25,pointRadius:5}]},options:{responsive:true,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,ticks:{precision:0},grid:{color:'#edf1ef'}},x:{grid:{display:false}}}}});}
function renderImpact(){const months=state.impact.months||[];const sum=k=>months.reduce((a,m)=>a+(Number(m[k])||0),0);document.querySelector('#lilysEvents').textContent=sum('events');document.querySelector('#lilysHours').textContent=sum('hours').toFixed(1).replace('.0','');document.querySelector('#lilysApplications').textContent=sum('applications');document.querySelector('#lilysCertifications').textContent=sum('certifications');}

document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>setCategory(b.dataset.category)));
document.querySelectorAll('[data-quick-category]').forEach(b=>b.addEventListener('click',()=>setCategory(b.dataset.quickCategory)));
document.querySelector('#resourceSearch').addEventListener('input',e=>{state.search=e.target.value;if(state.mode==='resources')renderResources();});
document.querySelector('#resourceMode').addEventListener('click',()=>setMode('resources'));document.querySelector('#opportunityMode').addEventListener('click',()=>setMode('opportunity'));
document.querySelector('#locateMe').addEventListener('click',()=>{if(!navigator.geolocation){alert('Location is not available in this browser.');return;}navigator.geolocation.getCurrentPosition(pos=>{const p=[pos.coords.latitude,pos.coords.longitude];L.circleMarker(p,{radius:8,color:'#155f52',fillColor:'#fff',fillOpacity:1,weight:4}).addTo(map).bindPopup('Your approximate location').openPopup();map.setView(p,15);},()=>alert('We could not access your location. You can still search by name or category.'));});
document.querySelector('#toggleAnalytics').addEventListener('click',()=>{const n=document.querySelector('#analyticsNotes');n.classList.toggle('hidden');document.querySelector('#toggleAnalytics').textContent=n.classList.contains('hidden')?'Show data notes':'Hide data notes';});

Promise.all([fetch('data/resources.json').then(r=>r.json()),fetch('data/wic-huntington.json').then(r=>r.json()),fetch('data/program-metrics.json').then(r=>r.json()),fetch('data/lilys-impact.json').then(r=>r.json())]).then(([resources,wic,program,impact])=>{state.resources=resources;state.wic=wic;state.program=program;state.impact=impact;renderResources();renderMetrics();renderCharts();renderImpact();}).catch(err=>{console.error(err);document.querySelector('#resourceList').innerHTML='<p>This site must be served from GitHub Pages or another web server so the JSON data files can load.</p>';});
